repos:
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v21.1.2'
    hooks:
    -   id: clang-format
        exclude: |
            (?x)^(
                .*/.pio/.*|
                .*\.proto|
                .*\.json
            )$

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v6.0.0'
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-json
  - id: check-toml
  - id: detect-private-key
