name: PlatformIO CI
on: [push]
permissions:
  contents: read # Read access to repository contents
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio intelhex

      # --- d1_mini builds using pio ci for all examples ---
      - name: Build d1_mini blink example
        run: pio run -e d1_mini_blink
      - name: Build d1_mini wifi_app example
        run: pio run -e d1_mini_wifi_app
      - name: Build d1_mini web-app example
        run: pio run -e d1_mini_web_app
      - name: Build d1_mini ha-app example
        run: pio run -e d1_mini_ha_app

      # --- esp32dev builds using pio run for all examples (leveraging platformio.ini) ---
      - name: Build esp32dev blink example
        run: pio run -e esp32dev_blink
      - name: Build esp32dev wifi-app example
        run: pio run -e esp32dev_wifi_app
      - name: Build esp32dev web-app example
        run: pio run -e esp32dev_web_app
      - name: Build esp32dev ha-app example
        run: pio run -e esp32dev_ha_app
